apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-deployment
  labels:
    app: test-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: registry.cn-hangzhou.aliyuncs.com/cyneck/test-service:2020-03-08-11-16-35
        ports:
        - containerPort: 8080
        env:
          - name: JAVA_OPTS
            value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5011
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: REGISTRY_URL
            value: http://eureka:password123@eureka-svc:8761/eureka/
          - name: SERVICE_HOST
            value: test-service
          - name: SERVICE_PORT
            value: "8080"
      # create docker registry secrects with:
      imagePullSecrets:          #Comment out to enable specific image pull secret
        - name: image-repo-key    # repleace it wity your specific docker registry secret

--- 

apiVersion: v1
kind: Service
metadata:
  name: test-service-svc #TODO: to specify your service name
  labels:
    app: test-service-svc
spec:
  selector:
    app: test-service #TODO: change label selector to match your backend pod
  ports:
  - protocol: TCP
    name: http
    port: 9001 #TODO: choose an unique port on each node to avoid port conflict
    targetPort: 8080
  type: NodePort
