apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: test-service-deployment
  labels:
    app: test-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: registry.cn-hangzhou.aliyuncs.com/cyneck/test-service:lasted
        ports:
        - containerPort: 9001
        env:
          - name: FETCHREGISTRY
            value: "false"
          - name: REGISTERWITHEUREKA
            value: "true"
          - name: REGISTRY_URL
            value: http://eureka:password123@eureka-svc:8761/eureka/
          - name: SERVICE_HOST
            value: test-service
          - name: SERVICE_PORT
            value: "9001"
      # create docker registry secrects with:
      imagePullSecrets:          #Comment out to enable specific image pull secret
        - name: image-repo-key    # repleace it wity your specific docker registry secret

--- 

apiVersion: v1
kind: Service
metadata:
  name: testservice-svc #TODO: to specify your service name
  labels:
    app: testservice-svc
spec:
  selector:
    app: testservice #TODO: change label selector to match your backend pod
  ports:
  - protocol: TCP
    name: http
    port: 9001 #TODO: choose an unique port on each node to avoid port conflict
    targetPort: 9001
  type: LoadBalancer
