package com.jrljs.microproduct.barometer.entity;
// Generated 2017-9-13 15:32:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * BarometerInfo generated by hbm2java
 */

public class BarometerInfo implements java.io.Serializable {

	private Long id;
	private String barometername;
	private String barometercode;
	private String status;
	private String winRatio;
	private String barometerReason;
	private Date createdTime;
	private Date updatedTime;

	public BarometerInfo() {
	}

	public BarometerInfo(String barometername, String barometercode, String status, Date createdTime,
			Date updatedTime) {
		this.barometername = barometername;
		this.barometercode = barometercode;
		this.status = status;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public BarometerInfo(String barometername, String barometercode, String status, String winRatio,
			String barometerReason, Date createdTime, Date updatedTime) {
		this.barometername = barometername;
		this.barometercode = barometercode;
		this.status = status;
		this.winRatio = winRatio;
		this.barometerReason = barometerReason;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBarometername() {
		return this.barometername;
	}

	public void setBarometername(String barometername) {
		this.barometername = barometername;
	}

	
	public String getBarometercode() {
		return this.barometercode;
	}

	public void setBarometercode(String barometercode) {
		this.barometercode = barometercode;
	}


	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	public String getWinRatio() {
		return this.winRatio;
	}

	public void setWinRatio(String winRatio) {
		this.winRatio = winRatio;
	}


	public String getBarometerReason() {
		return this.barometerReason;
	}

	public void setBarometerReason(String barometerReason) {
		this.barometerReason = barometerReason;
	}


	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}


	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
